---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: templates/custom.tex
geometry: margin=1in
 
fontfamily: mathpazo # tymes 
fontfamilyoptions: sc, osf
fontsize: 9pt
linkcolor: blue
urlcolor: blue

title: "CV"
author: Adrià Mitjavila Ventura

#academictitle: "MSc"
jobtitle: "Bioinformatician"
address: "Girona (Spain) - Milan (Italy)"
fontawesome: yes
email: adria.mitjavila94@gmail.com
github: amitjavilaventura
gitlab: amitjavilaventura
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
web: "amitjavilaventura.github.io"

keywords: Adria, Mitjavila, CV, academic, bioinformatician, LaTeX, Markdown

updated: yes
---

\vspace{3mm}

\small 
\emph{Biotechnologist living around computers, pursuing a PhD in Computational Biology and interested in data analysis to support experimental research as well as in pure computational experiments and in software/pipeline development.}

\normalsize

\vspace{2mm}
# Education \hrulefill

<!--
**PhD. Computational Biology**, *Scuola Europea di Medicina Molecolare*, Milan (Italy) \hfill {\small\emph{2019 - Present}}
-->

**MSc. Bioinformatics and Biostatistics**, *Universitat Oberta de Catalunya*, Online \hfill {\small\emph{2018 - Present}}

**MSc. Molecular Genetics and Biotechnology**, *Universidad de Sevilla*, Seville (Spain) \hfill {\small\emph{2017 - 2018}}

**BSc. Biotechnology**, *Universitat de Girona*, Girona (Spain)  \hfill {\small\emph{2012 - 2017}}

\vspace{2mm}
# Employment \hrulefill

*Istituto Europeo di Oncologia*  \hfill {\small\textbf{Milan (Italy)}}

<!--
* \footnotesize PhD Candidate in Computational Biology \hfill \emph{10/2019 - Present}
-->

* \footnotesize Bioinformatician \hfill \emph{07/2019 - Present}

```{r eval=FALSE, echo=FALSE}
*Universitat Oberta de Catalunya*  \hfill {\small\textbf{Online}}

* \footnotesize Master's thesis student \hfill \emph{10/2020 - Present}
```

*Instituto de Biomedicina de Sevilla* \hfill {\small\textbf{Seville (Spain)}}

* \footnotesize Research assistant \hfill \emph{07/2018 - 10/2018}

* \footnotesize Master's thesis student \hfill \emph{09/2017 - 07/2018}

*Institut d'Investigació Biomèdica de Girona* \hfill {\small\textbf{Girona (Spain)}}

* \footnotesize Research internship student \hfill \emph{07/2017 - 09/2017}

*Microbial. Sistemes i aplicacions analítiques, S.L.* \hfill {\small\textbf{Girona (Spain)}}

* \footnotesize Bachelor's thesis student \hfill \emph{01/2017 - 06/2017}

* \footnotesize Internship student \hfill \emph{09/2016 - 06/2017}

\vspace{2mm}
# Skills \hrulefill

\small \emph{Languages}: Catalan (*native*), Spanish (*native*), English (*IELTS 7.5 - C1*), Italian (*basic*)

\small \emph{Omics data analysis}: Microarray, RNA-seq, ChIP-seq, ATAC-seq, MNase-seq

\small \emph{Programming}: R/Bioconductor, Python, Bash

\small \emph{Other}: Snakemake, Conda, Docker, Git

\vspace{2mm}
# Publications \hrulefill

## Journal Articles

\footnotesize Begley *et al*. 2020 **Xrn1 influence on gene transcription results from the combination of general effects on elongating RNA pol II and gene-specific chromatin configuration**. *RNA Biology*. DOI: [10.1080/15476286.2020.1845504](https://doi.org/10.1080/15476286.2020.1845504).

\vspace{2mm}
# References \hrulefill

\footnotesize Available upon request.